/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssignedRouteImport } from './routes/assigned'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdBacklogRouteImport } from './routes/projects.$projectId.backlog'
import { Route as ProjectsProjectIdBoardRouteImport } from './routes/projects.$projectId.board'
import { Route as ProjectsProjectIdIssuesRouteImport } from './routes/projects.$projectId.issues'
import { Route as ProjectsProjectIdMembersRouteImport } from './routes/projects.$projectId.members'
import { Route as ProjectsProjectIdTicketsTicketIdRouteImport } from './routes/projects.$projectId.tickets.$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignedRoute = AssignedRouteImport.update({
  id: '/assigned',
  path: '/assigned',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdBacklogRoute =
  ProjectsProjectIdBacklogRouteImport.update({
    id: '/backlog',
    path: '/backlog',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdBoardRoute = ProjectsProjectIdBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdIssuesRoute = ProjectsProjectIdIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdMembersRoute =
  ProjectsProjectIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdTicketsTicketIdRoute =
  ProjectsProjectIdTicketsTicketIdRouteImport.update({
    id: '/tickets/$ticketId',
    path: '/tickets/$ticketId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assigned': typeof AssignedRoute
  '/login': typeof LoginRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/backlog': typeof ProjectsProjectIdBacklogRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/issues': typeof ProjectsProjectIdIssuesRoute
  '/projects/$projectId/members': typeof ProjectsProjectIdMembersRoute
  '/projects/$projectId/tickets/$ticketId': typeof ProjectsProjectIdTicketsTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assigned': typeof AssignedRoute
  '/login': typeof LoginRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/backlog': typeof ProjectsProjectIdBacklogRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/issues': typeof ProjectsProjectIdIssuesRoute
  '/projects/$projectId/members': typeof ProjectsProjectIdMembersRoute
  '/projects/$projectId/tickets/$ticketId': typeof ProjectsProjectIdTicketsTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assigned': typeof AssignedRoute
  '/login': typeof LoginRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/backlog': typeof ProjectsProjectIdBacklogRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/issues': typeof ProjectsProjectIdIssuesRoute
  '/projects/$projectId/members': typeof ProjectsProjectIdMembersRoute
  '/projects/$projectId/tickets/$ticketId': typeof ProjectsProjectIdTicketsTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assigned'
    | '/login'
    | '/projects/$projectId'
    | '/projects/$projectId/backlog'
    | '/projects/$projectId/board'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/members'
    | '/projects/$projectId/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assigned'
    | '/login'
    | '/projects/$projectId'
    | '/projects/$projectId/backlog'
    | '/projects/$projectId/board'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/members'
    | '/projects/$projectId/tickets/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/assigned'
    | '/login'
    | '/projects/$projectId'
    | '/projects/$projectId/backlog'
    | '/projects/$projectId/board'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/members'
    | '/projects/$projectId/tickets/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignedRoute: typeof AssignedRoute
  LoginRoute: typeof LoginRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assigned': {
      id: '/assigned'
      path: '/assigned'
      fullPath: '/assigned'
      preLoaderRoute: typeof AssignedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/backlog': {
      id: '/projects/$projectId/backlog'
      path: '/backlog'
      fullPath: '/projects/$projectId/backlog'
      preLoaderRoute: typeof ProjectsProjectIdBacklogRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/board': {
      id: '/projects/$projectId/board'
      path: '/board'
      fullPath: '/projects/$projectId/board'
      preLoaderRoute: typeof ProjectsProjectIdBoardRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/issues': {
      id: '/projects/$projectId/issues'
      path: '/issues'
      fullPath: '/projects/$projectId/issues'
      preLoaderRoute: typeof ProjectsProjectIdIssuesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/members': {
      id: '/projects/$projectId/members'
      path: '/members'
      fullPath: '/projects/$projectId/members'
      preLoaderRoute: typeof ProjectsProjectIdMembersRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/tickets/$ticketId': {
      id: '/projects/$projectId/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/projects/$projectId/tickets/$ticketId'
      preLoaderRoute: typeof ProjectsProjectIdTicketsTicketIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdBacklogRoute: typeof ProjectsProjectIdBacklogRoute
  ProjectsProjectIdBoardRoute: typeof ProjectsProjectIdBoardRoute
  ProjectsProjectIdIssuesRoute: typeof ProjectsProjectIdIssuesRoute
  ProjectsProjectIdMembersRoute: typeof ProjectsProjectIdMembersRoute
  ProjectsProjectIdTicketsTicketIdRoute: typeof ProjectsProjectIdTicketsTicketIdRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdBacklogRoute: ProjectsProjectIdBacklogRoute,
  ProjectsProjectIdBoardRoute: ProjectsProjectIdBoardRoute,
  ProjectsProjectIdIssuesRoute: ProjectsProjectIdIssuesRoute,
  ProjectsProjectIdMembersRoute: ProjectsProjectIdMembersRoute,
  ProjectsProjectIdTicketsTicketIdRoute: ProjectsProjectIdTicketsTicketIdRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignedRoute: AssignedRoute,
  LoginRoute: LoginRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
